sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '4'
  - '0.10'
before_install:
  - npm i -g npm@^3.0.0
before_script:
  - npm prune
script:
  - npm run validate
after_success:
  - 'curl -Lo travis_after_all.py https://git.io/travis_after_all'
  - python travis_after_all.py
  - 'export $(cat .to_export_back) &> /dev/null'
  - npm run report-coverage
branches:
  only:
    - master

